clear all
close all
load fdtd_sine_wave.mat
figure('Name', 'Time Steps of Electric Fields','Position',[00 500 1366 600])
set(gcf,'Color','white');
title(['E-field at Time Step ',int2str(n)],'FontSize',11,'Interpreter','latex','FontName','times new roman')
subplot(7,1,1)
plot(Ez1,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,2)
plot(Ez2,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,3)
plot(Ez3,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,4)
plot(Ez4,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,5)
plot(Ez5,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,6)
plot(Ez6,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gca,'XTickLabel',{})
set (gca,'FontName','times new roman')
subplot(7,1,7)
plot(Ez7,'Color','black','LineWidth',1.4)
axis([0 100 -1 1])
set(gcf,'Color','white');
set (gca,'FontName','times new roman')
axis([0 100 -.5 .5])
xlabel(' Cells in x-direction','FontSize',11,'Interpreter','latex','FontName','times new roman')
export_fig E1_fields '-pdf'  -nocrop -r300 -transparent  -native -painters -q101