Description of calc_kc
Home > ndsdp > calc_kc.m
calc_kc
PURPOSE
kc = calc_kc(k0, beta, Er, isImproper)
SYNOPSIS
function kc = calc_kc(k0, beta, Er, isImproper)
DESCRIPTION
 kc = calc_kc(k0, beta, Er, isImproper)
 if kc is real, it is positive for isImproper =0, and negative otherwise.
CROSS-REFERENCE INFORMATION
This function calls:
rep_args input is a number of arguments, some of which may be scalar and some of
This function is called by:
LS_space
calc_contours Written by Amit Hochman.
calc_residue_vect
sdp
second_deriv
SOURCE CODE
% kc = calc_kc(k0, beta, Er, isImproper)
% if kc is real, it is positive for isImproper =0, and negative otherwise.
function kc = calc_kc(k0, beta, Er, isImproper)
[mK0, mBeta, mEr, mIsImproper] = rep_args(k0, beta, Er, isImproper);
kc = sqrt((mK0.^2.*mEr-mBeta.^2));
bImproper = imag(kc)>0;
kc(bImproper) = -kc(bImproper).*(1-2*mIsImproper(bImproper));
kc(~bImproper) = kc(~bImproper).*(1-2*mIsImproper(~bImproper));