Description of gausslag
Home > ndsdp > gausslag.m
gausslag
PURPOSE
Laguerre polynomial
SYNOPSIS
function [x, w] = gausslag(n, alpha, beta)
DESCRIPTION
Laguerre polynomial
CROSS-REFERENCE INFORMATION
This function calls:
gauss GAUSS Gauss quadrature rule.
r_laguerre R_LAGUERRE Recurrence coefficients for monic generalized
This function is called by:
calc_contours Written by Amit Hochman.
SOURCE CODE
function [x, w] = gausslag(n, alpha, beta)
%Laguerre polynomial
ab=r_laguerre(n, beta);
xw = gauss(n, ab);
%Roots
x=xw(:,1);
w = xw(:,2).*exp(x).*abs(x).^(-beta);
alpha = alpha(:);
x = x(:).';
w = w(:).';
x = (1./alpha)*x;
w = (1./alpha)*w;
% debug
%x = linspace(min(x), 20/abs(alpha), n);