Description of gaussGen
Home > ndsdp > gaussGen.m
gaussGen
PURPOSE
SYNOPSIS
function [x, w] = gaussGen(n, minX, maxX, f)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
gauss GAUSS Gauss quadrature rule.
r_general
This function is called by:
calc_contours Written by Amit Hochman.
SOURCE CODE
function [x, w] = gaussGen(n, minX, maxX, f)
maxM = n*100;
eps0 = 1e-5;
mc = 10;
bInf = 0;
ab = r_general(n, maxM, eps0, mc, minX, maxX, f, bInf);
xw = gauss(n, ab);
%Roots
x = xw(:,1);
w = xw(:,2)./f(x);