Description of r_general
Home > ndsdp > r_general.m
r_general
PURPOSE
SYNOPSIS
function ab=r_general(N, maxM, eps0, mcIn, minX, maxX, f, bInf)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
mcdis MCDIS Multiple-component discretization procedure.
quadgp_gen QUADGP General-purpose quadrature routine.
This function is called by:
gaussGen
SOURCE CODE
function ab=r_general(N, maxM, eps0, mcIn, minX, maxX, f, bInf)
global mc mp iq idelta irout AB
mc = mcIn; mp=0; iq=0; idelta=1; irout=1;
x1 = linspace(minX, maxX, mc+1)';
x2 = x1(2:end);
x1 = x1(1:end-1);
if bInf
    mc = mc+2;
    x1 = [-20; x1; x2(end)];
    x2 = [x1(2); x2; 20];
end
AB= [x1 x2];
quadgp_local = @(x,y)quadgp_gen(x,y,f);
[ab,Mcap,kount]=mcdis(N*2,eps0,quadgp_local,maxM);